
-- config-sync cherry-pick
o.bind("CTRL + DOWN", "Close Mission Control", "omarchy-shell shell hide io.github.andyweiboan.missioncontrol")
o.bind("CTRL + UP", "Mission Control", "omarchy-shell shell toggle io.github.andyweiboan.missioncontrol '{}'")
o.bind("PRINT", "Omasnap", "/home/viniabdalla/.local/bin/omasnap")
o.bind("SUPER + ALT + C", "Claude", "xdg-terminal-exec claude")
o.bind("SUPER + ALT + O", "Toggle center mode", "/home/viniabdalla/.local/bin/toggle-center-mode")
o.bind("SUPER + ALT + Q", "Quick calculator", "menu-calc")
o.bind("SUPER + ALT + X", "Codex", "xdg-terminal-exec codex")
o.bind("SUPER + SHIFT + R", "Exit Gaming Mode", "/home/viniabdalla/.local/share/steam-launcher/leave-gamesmode")
o.bind("SUPER + SHIFT + S", "Omasnap", "/home/viniabdalla/.local/bin/omasnap")
o.bind("SUPER + SHIFT + T", "Send via Taildrop", "omarchy-shell shell toggle ryenski.taildrop")
o.bind("SUPER + SHIFT + Y", "ShelfClip paste", "shelfclip paste")
o.bind("SUPER + SHIFT + Z", "Extract text (OCR) from screenshot", "omarchy-capture-text")
o.bind("SUPER + Y", "ShelfClip toggle", "shelfclip toggle")
o.bind("CTRL + Y", "ShelfClip toggle", "/home/viniabdalla/Projects/gitprojects/Shelfclip/shelfclip toggle")
o.bind("SUPER + CTRL + UP", "Toggle workspace ribbon", "omarchy-shell crazybadger.workspace-ribbon toggle")
o.bind("SUPER + E", "Files", "xdg-open $HOME")
o.bind("SUPER + M", "Toggle game telemetry", "wtype -M shift -k F12 -m shift")
o.bind("SUPER + CTRL + ALT + S", "Spaces settings", "omarchy-shell tornikegomareli.spaces toggle")
