
-- config-sync cherry-pick
o.bind("CTRL + DOWN", "Close Mission Control", "omarchy-shell shell hide io.github.andyweiboan.missioncontrol")
o.bind("CTRL + UP", "Mission Control", "omarchy-shell shell toggle io.github.andyweiboan.missioncontrol '{}'")
o.bind("PRINT", "Screenshot", "omasnap")
o.bind("SUPER + ALT + C", "Claude", "xdg-terminal-exec claude")
o.bind("SUPER + ALT + O", "Toggle center mode", "/home/viniabdalla/.local/bin/toggle-center-mode")
o.bind("SUPER + ALT + Q", "Quick calculator", "menu-calc")
o.bind("SUPER + ALT + X", "Codex", "xdg-terminal-exec codex")
o.bind("SUPER + SHIFT + R", "Exit Gaming Mode", "/home/viniabdalla/.local/share/steam-launcher/leave-gamesmode")
o.bind("SUPER + SHIFT + S", "Screenshot", "omasnap")
o.bind("SUPER + SHIFT + T", "Send via Taildrop", "omarchy-shell shell toggle ryenski.taildrop")
o.bind("SUPER + SHIFT + Y", "ShelfClip paste", "shelfclip paste")
o.bind("SUPER + SHIFT + Z", "Extract text (OCR) from screenshot", "omarchy-capture-text")
o.bind("SUPER + Y", "ShelfClip toggle", "shelfclip toggle")
