-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0xED8F",
  mode = "1920x1080@60.21",
  position = "-1920x-218",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Beihai Century Joint Innovation Technology Co.Ltd Blizzard 27' 0000000000000",
  mode = "1920x1080@144.00",
  position = "0x0",
  scale = 1,
  vrr = 0,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:AU Optronics 0xED8F", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AU Optronics 0xED8F" })
hl.workspace_rule({ workspace = "3", monitor = "desc:Beihai Century Joint Innovation Technology Co.Ltd Blizzard 27' 0000000000000", default = true, persistent = true })
hl.workspace_rule({ workspace = "4", monitor = "desc:Beihai Century Joint Innovation Technology Co.Ltd Blizzard 27' 0000000000000" })
hl.workspace_rule({ workspace = "5", monitor = "desc:AU Optronics 0xED8F" })
hl.workspace_rule({ workspace = "6", monitor = "desc:AU Optronics 0xED8F" })
hl.workspace_rule({ workspace = "7", monitor = "desc:Beihai Century Joint Innovation Technology Co.Ltd Blizzard 27' 0000000000000" })
hl.workspace_rule({ workspace = "8", monitor = "desc:Beihai Century Joint Innovation Technology Co.Ltd Blizzard 27' 0000000000000" })
hl.workspace_rule({ workspace = "9", monitor = "desc:AU Optronics 0xED8F" })
