-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Ancor Communications Inc VS248 H8LMQS056303",
  mode = "1920x1080@60.00",
  position = "4154x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AOC 27G2G4 RFCN6XA002683",
  mode = "1920x1080@144.00",
  position = "2234x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:AOC 27G2G4 RFCN6XA002683", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AOC 27G2G4 RFCN6XA002683" })
hl.workspace_rule({ workspace = "3", monitor = "desc:AOC 27G2G4 RFCN6XA002683" })
hl.workspace_rule({ workspace = "4", monitor = "desc:Ancor Communications Inc VS248 H8LMQS056303", default = true, persistent = true })
hl.workspace_rule({ workspace = "5", monitor = "desc:Ancor Communications Inc VS248 H8LMQS056303" })
hl.workspace_rule({ workspace = "6", monitor = "desc:Ancor Communications Inc VS248 H8LMQS056303" })
hl.workspace_rule({ workspace = "7", monitor = "desc:AOC 27G2G4 RFCN6XA002683" })
hl.workspace_rule({ workspace = "8", monitor = "desc:AOC 27G2G4 RFCN6XA002683" })
hl.workspace_rule({ workspace = "9", monitor = "desc:AOC 27G2G4 RFCN6XA002683" })
