-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = {
        colors = { "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(0a0a0aee)", "rgba(0a0a0aee)", "rgba(0a0a0aee)" },
        angle = 90,
      },
      inactive_border = "rgb(272b30)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = {
        colors = { "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(8FECD5ee)", "rgba(0a0a0aee)", "rgba(0a0a0aee)", "rgba(0a0a0aee)" },
        angle = 90,
      },
      border_inactive = "rgb(272b30)",
    },
    groupbar = {
      col = {
        active = "rgba(8FECD599)",
        inactive = "rgba(48536288)",
      },
      text_color = "rgb(0a0a0a)",
      text_color_inactive = "rgba(D35F5Fff)",
    },
  },
  decoration = {
    rounding = 1,
    rounding_power = 3,
    shadow = {
      enabled = true,
      render_power = 6,
      range = 20,
      color = "rgba(00000052)",
    },
    blur = {
      enabled = true,
      size = 3,
      passes = 2,
    },
  },
})

hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(vesktop|Vesktop)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(code|VSCode|VSCodium)$",
  },
})
hl.window_rule({
  opacity = "1.0 override",
  no_dim = true,
  match = {
    class = "^(chromium|Chromium|google-chrome|Brave|brave-browser)$",
  },
})
