$color = rgba(5, 8, 10, 1)
$inner_color = rgba(5, 8, 10, 1)
$outer_color = rgba(220, 195, 249, 1)
$font_color = rgba(255, 246, 255, 1)
$placeholder_color = rgba(220, 226, 247, 0.7)
$check_color = rgba(197, 237, 193, 1)
